// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AiModelOption } from "./AiModelOption";

export type AiAvailableModels = { anthropic: Array<AiModelOption>, openai: Array<AiModelOption>, };
