// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AiProvider } from "./AiProvider";
import type { AiProviderConfig } from "./AiProviderConfig";

export type AiConfig = { provider: AiProvider, anthropic: AiProviderConfig, openai: AiProviderConfig, };
