// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Recommended model identifiers, surfaced to the UI as the dropdown
 * options. Both lists lead with the balanced default for that
 * provider; the rest are shortcuts to faster/cheaper or more
 * capable variants the operator can A/B against during the POC.
 */
export type AiModelOption = { id: string, label: string, 
/**
 * One-line UI hint — speed/cost/quality tradeoff in plain words.
 */
hint: string, };
