// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which provider the operator wants to use right now. `None` = AI
 * disabled; the UI hides the Generate button entirely in that state.
 */
export type AiProvider = "none" | "anthropic" | "openai";
