// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AiProviderConfig = { 
/**
 * Plaintext API key. Empty string = not configured. See module
 * docs for the eventual keychain migration.
 */
api_key: string, 
/**
 * Model identifier as accepted by the provider (e.g.
 * `claude-sonnet-4-6` or `gpt-5`). Empty string falls back to the
 * provider's recommended default at request time.
 */
model: string, };
