// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChaserSlot } from "./ChaserSlot";
import type { ColorMode } from "./ColorMode";
import type { FadeConfig } from "./FadeConfig";
import type { Pattern } from "./Pattern";
import type { Subdivision } from "./Subdivision";
import type { TempoSource } from "./TempoSource";

export type AmbientChaser = { id: string, name: string, enabled: boolean, slots: Array<ChaserSlot>, pattern: Pattern, color_mode: ColorMode, tempo: TempoSource, subdivision: Subdivision, 
/**
 * 0.0..=1.0 master multiplier on intensity.
 */
master: number, 
/**
 * Dim level applied when a slot is "off". 0 = blackout between flashes,
 * >0 = constant ambient with brighter "on" pulses.
 */
background: number, 
/**
 * Crossfade between successive steps. `enabled = false` snaps; otherwise
 * the chaser interpolates intensity and colour between frames.
 * `serde(default)` so old shows load with no fade.
 */
fade: FadeConfig, };
