// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One discovered Art-Net node, straight out of its ArtPollReply.
 */
export type ArtNetNodeInfo = { 
/**
 * Node IP as reported in the reply (falls back to the packet's
 * source address when the field is zeroed).
 */
ip: string, short_name: string, long_name: string, 
/**
 * "aa:bb:cc:dd:ee:ff", empty when the node sent a short packet.
 */
mac: string, 
/**
 * Firmware as "hi.lo".
 */
firmware: string, 
/**
 * Style code decoded to a label (Node / Controller / Media / ...).
 */
style: string, 
/**
 * 15-bit port-addresses this node OUTPUTS to DMX (what you patch
 * a controller at).
 */
output_universes: Array<number>, 
/**
 * Port-addresses the node reads as DMX input.
 */
input_universes: Array<number>, 
/**
 * Latest node diagnostic string (the "#0001 [ok]"-style report).
 */
node_report: string, 
/**
 * Distinguishes multiple logical nodes behind one IP.
 */
bind_index: number, };
