// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AudioBpmStatus = { running: boolean, device: string | null, 
/**
 * Smoothed estimate, one decimal. `None` until confident enough
 * (or while the input is silent).
 */
bpm: number | null, 
/**
 * 0..1 — autocorrelation peak height of the last estimate.
 */
confidence: number, 
/**
 * 0..1 input meter (−50..0 dBFS mapped linearly).
 */
level: number, 
/**
 * True for ~150 ms after each detected onset — UI beat flash.
 */
beat: boolean, 
/**
 * While true the worker writes confident estimates straight into
 * the Overall BPM (rounded to 0.1, with hysteresis).
 */
auto_apply: boolean, 
/**
 * While true the worker also anchors the chasers'/movements' beat
 * grid to the detected beat *phase* — steps land on the music, not
 * just at the right rate. Ignored while the VDJ bridge is enabled
 * (that clock wins).
 */
phase_sync: boolean, error: string | null, };
