// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BlackoutConfig = { 
/**
 * Target state. Persisted so a show that ships with blackout still
 * boots blacked-out the next time the operator opens it.
 */
active: boolean, 
/**
 * Fade-to-black time when the user toggles blackout *on*. ms.
 */
fade_in_ms: number, 
/**
 * Fade-from-black time when the user toggles blackout *off*. ms.
 */
fade_out_ms: number, };
