// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlackoutFixture } from "./BlackoutFixture";

export type BlackoutConfig = { 
/**
 * Target state. Persisted so a show that ships with blackout still
 * boots blacked-out the next time the operator opens it.
 */
active: boolean, 
/**
 * Fade-to-black time when the user toggles blackout *on*. ms.
 */
fade_in_ms: number, 
/**
 * Fade-from-black time when the user toggles blackout *off*. ms.
 */
fade_out_ms: number, 
/**
 * Fixtures affected by blackout, with the specific channel roles
 * that should be driven to 0 when the button is engaged. Empty
 * list = "auto mode": every patched fixture in the show gets the
 * sensible default (intensity → 0, or RGB → 0 for fixtures without
 * an intensity channel, plus strobe → 0). Pan/tilt/zoom etc. are
 * never touched by auto mode — a moving head should stay parked
 * where it was, just dark.
 */
fixtures: Array<BlackoutFixture>, };
