// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BlackoutFixture = { fixture_id: string, 
/**
 * Role labels (`"intensity"`, `"red"`, `"strobe"`, …) that should
 * be lerped to 0 when blackout is on. Empty list = auto behaviour
 * for this fixture (intensity-or-RGB + strobe).
 */
channels_to_zero: Array<string>, };
