// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlindFixture } from "./BlindFixture";

export type BlindConfig = { 
/**
 * Time to ramp up while the button is held. Short by default —
 * halogens turn on fast.
 */
fade_in_ms: number, 
/**
 * Cool-down time after the button is released. Long by default —
 * halogens take ages to fade out.
 */
fade_out_ms: number, 
/**
 * Fixtures affected by blind. Each entry can list channel role names
 * to drive at 255 when pressed; if no roles are listed we use the
 * default halogen warm-white behaviour. Empty list = blind does
 * nothing (safe default before the user has configured anything).
 */
fixtures: Array<BlindFixture>, };
