// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BlindFixture = { fixture_id: string, 
/**
 * Optional list of role names the blind should drive to 255 when the
 * button is held. Standard roles (`"intensity"`, `"red"`, `"strobe"`,
 * …) plus the inner string of any `Other("foo")` channel — same
 * labels the UI shows next to each slider. Empty means: fall back to
 * the default halogen behaviour (warm-white on intensity + RGB).
 */
channels_at_full: Array<string>, };
