// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlindChange } from "./BlindChange";
import type { EngineStats } from "./EngineStats";
import type { MasterChange } from "./MasterChange";
import type { ProgrammerStatus } from "./ProgrammerStatus";
import type { SceneActiveChange } from "./SceneActiveChange";

/**
 * Tagged union of every push event the bridge sends to mobile clients.
 * Matches `BridgeEvent` on the JS side. Adding a variant here means
 * clients can ignore it (forward-compat) — never *remove* a variant
 * without bumping a protocol version.
 */
export type BridgeEvent = { "type": "show_updated" } | { "type": "scene_active_changed" } & SceneActiveChange | { "type": "master_changed" } & MasterChange | { "type": "blind_changed" } & BlindChange | { "type": "programmer_changed" } & ProgrammerStatus | { "type": "engine_stats" } & EngineStats;
