// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PairingState } from "./PairingState";

/**
 * Public-facing snapshot of the bridge's runtime state. Drives the
 * "Remote" tab in the desktop UI.
 */
export type BridgeStatus = { running: boolean, host_ip: string | null, port: number | null, clients_connected: number, paired_devices: number, pairing: PairingState | null, last_error: string | null, };
