// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What glyph to draw on the Stream Deck tile.
 */
export type ButtonIcon = "none" | "play" | "stage" | "orbit" | "bolt" | "eye" | "tap" | "metronome" | "loop";
