// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What pressing a configured button should do.
 *
 * The variants mirror the entire set of actions the hardcoded
 * controllers already dispatch (chaser toggle, scene recall,
 * blackout, blind, tap, BPM override toggle) plus the new
 * loop-group play/stop pair that the Sequence Groups feature adds.
 * Indexed variants (`*ByIndex`) refer to the n-th item of the
 * corresponding show list (chaser/movement/scene). They survive a
 * rename of the underlying entity, which makes the "factory layout"
 * stable across shows — useful for muscle memory across rigs.
 */
export type ButtonAction = { "type": "none" } | { "type": "toggle_chaser", id: string, } | { "type": "toggle_chaser_by_index", index: number, } | { "type": "toggle_movement", id: string, } | { "type": "toggle_movement_by_index", index: number, } | { "type": "recall_scene", id: string, } | { "type": "recall_scene_by_index", index: number, } | { "type": "blackout" } | { "type": "blind" } | { "type": "tap" } | { "type": "toggle_overall_bpm" } | { "type": "bump_active_chaser_bpm", delta: number, } | { "type": "start_loop_group", id: string, } | { "type": "start_loop_group_by_index", index: number, } | { "type": "stop_loop_group" };
