// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LaunchpadBinding } from "./LaunchpadBinding";
import type { StreamDeckBinding } from "./StreamDeckBinding";

/**
 * Top-level config that lives off the show file.
 */
export type ButtonBindings = { 
/**
 * When `false` (default), the surface controllers ignore the
 * per-binding lists and use the built-in factory layout. When
 * `true`, the lists below are authoritative — a missing entry
 * means "dark / no action" for that physical button.
 */
custom_enabled: boolean, launchpad: Array<LaunchpadBinding>, streamdeck: Array<StreamDeckBinding>, };
