// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How the LED / tile should reflect the action's "is it running" state.
 */
export type ButtonActiveMode = "auto" | "always_idle" | "always_active";
