// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Cadence = { "type": "every_step" } | { "type": "every_n_steps", n: number, } | { "type": "per_slot" } | { "type": "alternate_slots" } | { "type": "chase_per_color" };
