// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ChannelRole = "intensity" | "red" | "green" | "blue" | "white" | "amber" | "uv" | "cyan" | "magenta" | "yellow" | "pan" | "pan_fine" | "tilt" | "tilt_fine" | "color_wheel" | "gobo" | "strobe" | "zoom" | "focus" | "iris" | "shutter" | { "other": string };
