// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelRole } from "./ChannelRole";

export type ChannelDefinition = { role: ChannelRole, default: number, };
