// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One labelled segment of a channel's DMX value space (Freestyler-style).
 * Inclusive on both ends. The optional `image` is a base64 data URL or
 * a legacy filesystem path (resolved by the same helper as the fixture
 * thumbnail), shown as a thumbnail on the range button.
 */
export type ChannelRange = { from: number, to: number, label: string, image: string | null, 
/**
 * Original on-disk path of the image when imported from another
 * app (Freestyler etc.). Informational; the UI renders `image`.
 */
image_path: string | null, };
