// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelRange } from "./ChannelRange";
import type { ChannelRole } from "./ChannelRole";

export type ChannelDefinition = { role: ChannelRole, 
/**
 * Human-friendly label shown in the UI when present (e.g.
 * "Color Wheel", "Strobe / Shutter"). Falls back to `role.label()`.
 */
name: string | null, 
/**
 * Tooltip / longer explanation, e.g. "Speed lento (0) → rápido (255)".
 */
description: string | null, 
/**
 * DMX value ranges this channel accepts, each tagged with a label
 * and an optional thumbnail. Manufacturers describe color wheels,
 * gobo wheels, strobe modes etc. as ranges; we surface them as
 * click-to-set buttons in the editor instead of forcing the user
 * to dial a slider to the right value.
 * Empty (or missing) → channel is purely continuous, slider only.
 */
ranges: Array<ChannelRange>, default: number, };
