// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Cadence } from "./Cadence";
import type { PaletteRotation } from "./PaletteRotation";
import type { Rgb } from "./Rgb";

export type ColorMode = { "type": "disabled" } | { "type": "single", color: Rgb, } | { "type": "two_color_cadence", color_a: Rgb, color_b: Rgb, cadence: Cadence, } | { "type": "palette", colors: Array<Rgb>, rotation: PaletteRotation, } | { "type": "rainbow", speed: number, spread: number, };
