// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type D2xxDeviceInfo = { serial_number: string, description: string, vendor_id: number, product_id: number, 
/**
 * True if some other process / kernel driver currently has it claimed.
 */
port_open: boolean, };
