// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DraftStep } from "./DraftStep";

/**
 * Shape returned to the frontend as a preview before applying.
 * Mirrors `Scene`/`SceneStep`/`SceneFixture` from the show domain
 * but stays decoupled so changes there don't churn the LLM contract.
 */
export type DraftScene = { name: string, steps: Array<DraftStep>, };
