// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DraftValue } from "./DraftValue";

export type DraftFixture = { fixture_id: string, values: Array<DraftValue>, };
