// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DraftFixture } from "./DraftFixture";

export type DraftStep = { name: string | null, fade_in_ms: number, hold_ms: number, fixtures: Array<DraftFixture>, };
