// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EngineStats = { fps: number, frames_total: number, late_frames: number, max_frame_micros: number, };
