// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FadeCurve } from "./FadeCurve";

export type FadeConfig = { enabled: boolean, 
/**
 * Fraction of the step duration spent fading. `0.0` snaps (no fade),
 * `1.0` fades across the whole step. Clamped to `[0, 0.9]` at runtime
 * so the fade always finishes before the next step transition.
 */
amount: number, curve: FadeCurve, };
