// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single manual fixture-channel write. The mobile remote sends these
 * in batches (`set_fixture_channels`) so an RGB color or a multi-fixture
 * selection lands as one atomic update with a single `PROGRAMMER_EVENT`
 * instead of N round-trips that would flicker as the snapshots race.
 */
export type FixtureChannelWrite = { fixture_id: string, channel_offset: number, value: number, };
