// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FixtureInstance = { id: string, definition_id: string, mode_index: number, universe: number, 
/**
 * 1-based DMX start address.
 */
address: number, label: string | null, 
/**
 * Position on the 2D stage grid in arbitrary units.
 */
position: [number, number], };
