// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelDefinition } from "./ChannelDefinition";
import type { PanTiltRange } from "./PanTiltRange";

export type FixtureMode = { name: string, channels: Array<ChannelDefinition>, 
/**
 * Physical pan range. `None` lets consumers pick a sensible default
 * (`PanTiltRange::default_pan`). Once a fixture is declared with
 * concrete ranges those win, so user-edited library JSON doesn't get
 * overwritten by app-side defaults.
 */
pan_range: PanTiltRange | null, tilt_range: PanTiltRange | null, };
