// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FixtureMode } from "./FixtureMode";

export type FixtureDefinition = { id: string, manufacturer: string, name: string, modes: Array<FixtureMode>, 
/**
 * Optional path (relative to the library directory) of an image used to
 * identify the fixture in the UI. `None` for definitions that ship without
 * art; persisted alongside the JSON definition file.
 */
image: string | null, };
