// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MidiControlTarget } from "./MidiControlTarget";

/**
 * One "MIDI learn" mapping: any note/CC from any controller connected
 * through the MIDI hub, bound to an action or a continuous target.
 * Independent of the Launchpad/Stream Deck factory layouts and always
 * active (no `custom_enabled` gate).
 */
export type GenericMidiBinding = { id: string, label: string, 
/**
 * `true` = ControlChange, `false` = NoteOn/NoteOff.
 */
is_cc: boolean, 
/**
 * 0-based MIDI channel.
 */
channel: number, 
/**
 * Note number or CC number.
 */
data1: number, target: MidiControlTarget, };
