// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlackoutConfig } from "./BlackoutConfig";
import type { BlindConfig } from "./BlindConfig";
import type { MasterConfig } from "./MasterConfig";

export type GlobalsConfig = { blackout: BlackoutConfig, blind: BlindConfig, 
/**
 * Which fixture channels the master fader scales. Default behaviour
 * (`MasterConfig::default()` with `fixtures` empty) is "auto":
 * scale only the intensity-or-RGB channel of every patched fixture,
 * leaving pan/tilt/zoom/colour-wheel/etc. untouched. The per-
 * fixture override lets the operator extend or narrow that set.
 */
master: MasterConfig, };
