// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlackoutConfig } from "./BlackoutConfig";
import type { BlindConfig } from "./BlindConfig";

export type GlobalsConfig = { blackout: BlackoutConfig, blind: BlindConfig, };
