// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ButtonAction } from "./ButtonAction";
import type { ButtonActiveMode } from "./ButtonActiveMode";

/**
 * Per-button binding for the Launchpad MK2 grid.
 */
export type LaunchpadBinding = { 
/**
 * The MK2 addresses every pad by a unique number. We accept both
 * grid NoteOn pads (notes 11..=88) and the top-row CCs (104..=111)
 * behind one byte; `is_cc` disambiguates.
 */
note: number, is_cc: boolean, action: ButtonAction, 
/**
 * Free-text human label. Not drawn on hardware (the MK2 is just
 * LEDs) but shown in the binding list UI so the operator can
 * document what's wired up.
 */
label: string, 
/**
 * MK2 colour palette index for the "off / available" state.
 * 0 = dark. Values map directly to the MK2 palette §11.
 */
color_dim: number, 
/**
 * MK2 colour palette index for the "active / flash" state. When
 * the button is showing as active the hardware blinks between
 * `color_dim` and `color_bright` at ~1 Hz.
 */
color_bright: number, active_mode: ButtonActiveMode, };
