// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A control captured by learn mode, ready for the UI to bind.
 */
export type LearnedControl = { is_cc: boolean, channel: number, data1: number, 
/**
 * Human-readable summary ("CC 21 · ch 1") for the UI chip.
 */
description: string, };
