// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One playlist slot: a scene recall or a snapshot apply.
 */
export type LoopEntry = { "type": "scene", id: string, } | { "type": "snapshot", id: string, };
