// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MasterFixture = { fixture_id: string, 
/**
 * Role labels the master should scale on this fixture. Empty list
 * = "use the auto channel set for THIS fixture" (intensity-or-RGB).
 * Operators tick e.g. `["intensity", "white"]` to also dim the
 * extra LED chips on an RGBWAP par.
 */
channels_to_scale: Array<string>, };
