// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MasterFixture } from "./MasterFixture";

export type MasterConfig = { 
/**
 * Fixtures with custom master scaling. Empty = "auto mode" applies
 * to every patched fixture. Auto mode means: scale intensity (or
 * RGB if there's no intensity channel). Strobe is intentionally
 * *not* included in auto — operators expect the master to dim the
 * look, not slow strobes.
 */
fixtures: Array<MasterFixture>, };
