// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ButtonAction } from "./ButtonAction";

/**
 * What a learned generic MIDI control drives.
 */
export type MidiControlTarget = { "type": "action", action: ButtonAction, } | { "type": "master" };
