// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MidiDeviceInfo = { name: string, 
/**
 * `true` if this device shows up on the input side (most surfaces
 * expose both, but a few output-only devices like dumb DMX MIDI
 * boxes wouldn't).
 */
has_input: boolean, has_output: boolean, };
