// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MidiMessage } from "./MidiMessage";

export type MidiStatus = { connected: string | null, has_output: boolean, last_event: MidiMessage | null, };
