// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Single message captured off the input port. Keeps the raw bytes plus a
 * human-readable label so the UI can render either depending on user
 * preference (and so a future "learn" mode has the bytes intact).
 */
export type MidiMessage = { status: number, data1: number | null, data2: number | null, label: string, 
/**
 * Wall-clock millis since unix epoch — handy for the UI log.
 */
timestamp_ms: bigint, };
