// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Direction } from "./Direction";
import type { MovementSlot } from "./MovementSlot";
import type { Shape } from "./Shape";
import type { SpreadMode } from "./SpreadMode";
import type { Subdivision } from "./Subdivision";
import type { TempoSource } from "./TempoSource";

export type MovementGenerator = { 
/**
 * Stable id, used to preserve runtime phase across edits and to
 * dispatch toggle actions from surfaces (Launchpad, future scripts).
 * Defaulted on deserialise so legacy show files without an id are
 * migrated transparently — the loader assigns a fresh uuid on first
 * load and saves it back on the next persist.
 */
id: string, 
/**
 * User-visible label, like "Slow circle" or "Strobe sweep".
 */
name: string, enabled: boolean, fixtures: Array<MovementSlot>, shape: Shape, 
/**
 * `0.0..=1.0` width scale applied after the shape produces normalised
 * `[-1, 1]` output.
 */
size_x: number, size_y: number, 
/**
 * `-1.0..=1.0` centre offset within the normalised pan/tilt space.
 */
center_x: number, center_y: number, 
/**
 * 2D rotation in degrees applied before size/centre.
 */
rotation_deg: number, spread_mode: SpreadMode, tempo: TempoSource, subdivision: Subdivision, direction: Direction, };
