// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MovementSlot = { fixture_id: string, 
/**
 * 0.0..=1.0 phase shift applied to this fixture's place in the loop.
 * `SpreadMode::Even` overwrites this on every fixture-list change; in
 * `Manual` mode the user owns it.
 */
phase_offset: number, 
/**
 * Mirror this fixture horizontally relative to the shape's natural
 * pan output. Useful when half a rig is hung facing the other way.
 */
invert_pan: boolean, invert_tilt: boolean, };
