// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OutputBindingConfig } from "./OutputBindingConfig";

export type OutputsConfig = { bindings: Array<OutputBindingConfig>, 
/**
 * Stable component identifier (CID) for sACN, persisted across runs.
 * Generated on first save if missing.
 */
sacn_cid: [number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number] | null, };
