// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OutputBindingConfig = { "kind": "mock", id: string, universes: Array<number>, } | { "kind": "art_net", id: string, target: string, universes: Array<number>, } | { "kind": "sacn", id: string, source_name: string, priority: number, universes: Array<number>, } | { "kind": "enttec_usb", id: string, port: string, universes: Array<number>, } | { "kind": "open_dmx", id: string, port: string, universes: Array<number>, } | { "kind": "open_dmx_ftdi", id: string, 
/**
 * FTDI device serial number (stable across reboots).
 */
serial: string, universes: Array<number>, 
/**
 * DTR pin state. Wiring varies between Open DMX clones; some need
 * HIGH, some LOW. Default LOW (matches QLC+/libftdi).
 */
dtr_high: boolean, 
/**
 * RTS pin state. See `dtr_high`.
 */
rts_high: boolean, };
