// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PairedDevice = { id: string, name: string, 
/**
 * SHA-256(token) base64-url-no-pad. The plaintext token never
 * touches disk — once we've returned it to the device on `/pair`
 * we throw it away.
 */
token_hash: string, 
/**
 * UNIX seconds of pairing. Used by the UI to show "paired 3 days
 * ago" without stuffing relative time into the JSON.
 */
created_at: bigint, 
/**
 * UNIX seconds of last successful auth. Bumped each time a WS
 * from this device opens. Useful for the operator deciding which
 * row to revoke when devices.json grows.
 */
last_seen: bigint | null, };
