// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PairingState = { pin: string, 
/**
 * SVG markup for the QR. The frontend can drop this straight
 * into a <div dangerouslySetInnerHTML> — saves shipping a JS
 * QR library and keeps the source of truth in Rust.
 */
qr_svg: string, remaining_secs: bigint, 
/**
 * Pre-built `dmxctrl://pair?...` URL used as the QR payload —
 * also handy for "share with iMessage" debugging.
 */
pair_url: string, };
