// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PanTiltRange = { 
/**
 * 16-bit DMX value at the "negative" extreme of the normalised range.
 */
min: number, 
/**
 * 16-bit DMX value at the "positive" extreme of the normalised range.
 */
max: number, 
/**
 * Physical sweep covered by `min..=max`, used by the UI to label the
 * preview. Not used in the DMX math itself (the math is pure-numeric).
 */
physical_degrees: number, };
