// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PatchConflict } from "./PatchConflict";
import type { PatchProblem } from "./PatchProblem";

export type PatchReport = { conflicts: Array<PatchConflict>, problems: Array<PatchProblem>, };
