// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PatchConflict = { fixture_a: string, fixture_b: string, universe: number, 
/**
 * 1-based start of the overlap.
 */
overlap_start: number, overlap_len: number, };
