// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Pattern = { "type": "all_together" } | { "type": "alternate" } | { "type": "chase" } | { "type": "chase_reverse" } | { "type": "ping_pong" } | { "type": "random" } | { "type": "wave" } | { "type": "wave_reverse" } | { "type": "build" } | { "type": "build_reverse" } | { "type": "center_out" } | { "type": "symmetric" };
