// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TouchedFixture } from "./TouchedFixture";

export type ProgrammerStatus = { 
/**
 * IDs of touched fixtures. Kept as a flat list for the existing
 * "fixture count" widgets that were written before per-channel
 * tracking landed.
 */
touched: Array<string>, 
/**
 * Per-fixture detail: which channels are touched on each. Empty
 * when nothing has been touched. The UI uses this to highlight
 * just the dialed-in channels on the stage canvas.
 */
channels: Array<TouchedFixture>, };
