// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One discovered responder, decorated with the descriptive PIDs we
 * managed to GET (all best-effort — a device that ignores
 * DEVICE_LABEL still shows up with its UID).
 */
export type RdmDeviceInfo = { 
/**
 * "MMMM:DDDDDDDD" hex UID.
 */
uid: string, model: string, manufacturer: string, label: string, software_version: string, 
/**
 * 1-based DMX start address (0 = unknown / footprint 0).
 */
dmx_start_address: number, 
/**
 * Channels consumed by the current personality.
 */
footprint: number, personality: string, };
