// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SceneChannel } from "./SceneChannel";

export type SceneFixture = { fixture_id: string, values: Array<SceneChannel>, };
