// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SceneFixture } from "./SceneFixture";
import type { SceneFxState } from "./SceneFxState";

/**
 * One frame of a multi-step scene. Holds for `hold_ms` after fading in
 * over `fade_in_ms`. The hold portion is what makes a step distinct
 * from the next — without hold, two steps with similar values would
 * just look like a long fade.
 *
 * Each step carries its own FX context (chaser/movement) captured at
 * record time. When the playback transitions into this step, the
 * engine applies that context (toggling chasers/movement to match).
 * `Inherit` means "leave whatever's running alone" — useful when most
 * steps share the same chaser and you only want one or two steps to
 * switch it.
 */
export type SceneStep = { id: string, 
/**
 * Optional human label. UI defaults to "Step N" when empty.
 */
name: string | null, fade_in_ms: number, 
/**
 * How long to sit on the step's target after the fade finishes.
 * `0` = transition straight into the next step's fade. Single-step
 * scenes effectively ignore this.
 */
hold_ms: number, fixtures: Array<SceneFixture>, chaser_state: SceneFxState, movement_state: SceneFxState, };
