// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LoopEntry } from "./LoopEntry";
import type { Subdivision } from "./Subdivision";

export type SceneLoopGroup = { id: string, name: string, 
/**
 * Legacy scene-only list (pre-snapshot groups). Lifted into
 * `entries` on load via [`SceneLoopGroup::migrate_legacy`] and
 * never re-serialised afterwards.
 */
scene_ids: Array<string>, 
/**
 * Playlist entries in playback order. The cycle loops back to
 * index 0 after the last entry. Entries whose target no longer
 * exists are silently skipped at playback time, so deleting a
 * scene/snapshot doesn't strand the group.
 */
entries: Array<LoopEntry>, 
/**
 * Optional override of how long to dwell on each entry before
 * advancing, in milliseconds. `0` (default) means "use the scene's
 * own total cycle time" (or 2 s for snapshots). Ignored while
 * `sync_to_bpm` is active with the Overall BPM enabled.
 */
hold_ms_override: number, 
/**
 * When true AND the Overall BPM override is on, each entry dwells
 * exactly one `subdivision` worth of beats at the global tempo, so
 * the playlist advances on the music.
 */
sync_to_bpm: boolean, 
/**
 * Musical length of one entry when `sync_to_bpm` drives the dwell.
 * Expressed in the same quarter-note multiples the chasers use
 * (`Four` = one 4/4 bar — the default a DJ expects).
 */
subdivision: Subdivision, };
