// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SceneFixture } from "./SceneFixture";
import type { SceneFxState } from "./SceneFxState";
import type { SceneStep } from "./SceneStep";

export type Scene = { id: string, name: string, 
/**
 * Ordered list of frames. Playback loops back to 0 after the last.
 * Empty list = scene is a placeholder; recall does nothing visible.
 */
steps: Array<SceneStep>, 
/**
 * Legacy: pre-iteration-4 scenes carried a single FX state at the
 * scene level. Migrated into `steps[0]` on load via `migrate_legacy`
 * and never re-emitted. The skip-if-inherit guard keeps fresh saves
 * clean.
 */
chaser_state: SceneFxState, movement_state: SceneFxState, 
/**
 * Legacy: pre-multi-step scenes stored a single fade time at the
 * scene level. Lifted into `steps[0].fade_in_ms` on load via
 * `migrate_legacy`; never re-serialised after migration.
 */
fade_in_ms: number, 
/**
 * Legacy direct fixtures list. Same lift-and-clear semantics.
 */
fixtures: Array<SceneFixture>, };
