// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-layer FX state baked into a scene. Captured at record time,
 * re-applied on recall, mirrors the user's mental model of "the look
 * I saved" being the full rig context, not just the dimmer/colour
 * snapshot.
 */
export type SceneFxState = { "type": "inherit" } | { "type": "disabled" } | { "type": "enabled", id: string, };
