// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SceneActiveChange = { active_scene_id: string | null, step_index: number | null, };
