// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SceneLoopGroup = { id: string, name: string, 
/**
 * Scene IDs in playback order. The cycle loops back to index 0
 * after the last entry. Entries that point at scenes that no
 * longer exist are silently skipped at playback time so deleting
 * a scene doesn't strand the group.
 */
scene_ids: Array<string>, 
/**
 * Optional override of how long to dwell on each scene before
 * advancing, in milliseconds. `0` (default) means "use the scene's
 * own total cycle time" — sum of all of its steps' fade + hold —
 * which is the natural choice for hand-crafted multi-step scenes.
 * Set to a positive value when every scene in the group should
 * hold for the same duration regardless of how it was recorded.
 */
hold_ms_override: number, };
