// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SerialPortInfo = { name: string, vid: number | null, pid: number | null, manufacturer: string | null, product: string | null, 
/**
 * True if VID matches FTDI; Enttec USB Pro is the typical match here.
 */
looks_like_enttec: boolean, };
