// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WaveFunction } from "./WaveFunction";

export type Shape = { "type": "circle" } | { "type": "polygon", sides: number, } | { "type": "star", points: number, inner_ratio: number, } | { "type": "figure_eight" } | { "type": "line_horizontal" } | { "type": "line_vertical" } | { "type": "sine_combo", pan: WaveFunction, tilt: WaveFunction, };
