// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AmbientChaser } from "./AmbientChaser";
import type { FixtureInstance } from "./FixtureInstance";
import type { GlobalsConfig } from "./GlobalsConfig";
import type { MovementGenerator } from "./MovementGenerator";
import type { OutputsConfig } from "./OutputsConfig";

export type ShowFileV1 = { 
/**
 * Always 1 in this version. Bumping this requires a migration.
 */
version: number, name: string, fixtures: Array<FixtureInstance>, outputs: OutputsConfig, 
/**
 * Ambient Chasers — generative low-priority chases. Optional in the
 * schema (`#[serde(default)]`) so shows saved before the chaser module
 * existed load with an empty list, no migration required.
 */
chasers: Array<AmbientChaser>, 
/**
 * Legacy single-movement field. Pre-multi-movement show files used
 * `movement: { … }`; the loader lifts whatever is here into the first
 * slot of `movements` and clears it. `skip_serializing_if` makes sure
 * fresh saves never re-emit the legacy key.
 */
movement: MovementGenerator | null, 
/**
 * Movement Generators. Same shape/role as `chasers`: a list of
 * independently-editable presets. The runtime enforces "one enabled
 * at a time" through `toggle_movement_impl`, mirroring chasers.
 */
movements: Array<MovementGenerator>, 
/**
 * Global buttons (Blackout + Blind). Persisted so the user's fade
 * times and blinder fixture list survive a restart.
 */
globals: GlobalsConfig, };
