// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AmbientChaser } from "./AmbientChaser";
import type { ButtonBindings } from "./ButtonBindings";
import type { FixtureDefinition } from "./FixtureDefinition";
import type { FixtureInstance } from "./FixtureInstance";
import type { GlobalsConfig } from "./GlobalsConfig";
import type { MovementGenerator } from "./MovementGenerator";
import type { OutputsConfig } from "./OutputsConfig";
import type { Scene } from "./Scene";
import type { SceneLoopGroup } from "./SceneLoopGroup";

export type ShowFileV1 = { 
/**
 * Always 1 in this version. Bumping this requires a migration.
 */
version: number, name: string, fixtures: Array<FixtureInstance>, outputs: OutputsConfig, 
/**
 * Ambient Chasers — generative low-priority chases. Optional in the
 * schema (`#[serde(default)]`) so shows saved before the chaser module
 * existed load with an empty list, no migration required.
 */
chasers: Array<AmbientChaser>, 
/**
 * Legacy single-movement field. Pre-multi-movement show files used
 * `movement: { … }`; the loader lifts whatever is here into the first
 * slot of `movements` and clears it. `skip_serializing_if` makes sure
 * fresh saves never re-emit the legacy key.
 */
movement: MovementGenerator | null, 
/**
 * Movement Generators. Same shape/role as `chasers`: a list of
 * independently-editable presets. The runtime enforces "one enabled
 * at a time" through `toggle_movement_impl`, mirroring chasers.
 */
movements: Array<MovementGenerator>, 
/**
 * Global buttons (Blackout + Blind). Persisted so the user's fade
 * times and blinder fixture list survive a restart.
 */
globals: GlobalsConfig, 
/**
 * Recorded scenes — Phase 4 MVP. Each entry is a per-fixture
 * per-channel snapshot the operator can recall with a fade.
 */
scenes: Array<Scene>, 
/**
 * Named playlists of scenes that loop on their own. Each group
 * holds an ordered list of scene IDs and cycles through them
 * using each scene's own fade/hold (or a per-group hold override).
 */
scene_loop_groups: Array<SceneLoopGroup>, 
/**
 * User-customised Launchpad / Stream Deck button assignments.
 * `custom_enabled = false` (default) means the surface
 * controllers use the built-in factory layout; flipping it to
 * true makes the per-surface lists below authoritative.
 */
button_bindings: ButtonBindings, 
/**
 * Snapshot of the fixture definitions referenced by this show.
 * Saved alongside `fixtures` so a `.json` is portable across
 * machines: open the file on a fresh install and the rig appears
 * without needing to ship the user's library directory too. The
 * commands layer fills this on save (only the defs actually used)
 * and merges it into the runtime library on open. Empty for shows
 * saved before this field existed — the loader falls back to the
 * installed library exactly as it always did.
 */
library: Array<FixtureDefinition>, };
