// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SceneFxState } from "./SceneFxState";
import type { SnapshotUniverse } from "./SnapshotUniverse";

export type Snapshot = { id: string, name: string, universes: Array<SnapshotUniverse>, 
/**
 * Grand master fader at capture time.
 */
master: number, 
/**
 * Chaser running at capture time (`Disabled` = none was on).
 */
chaser_state: SceneFxState, 
/**
 * Movement generator running at capture time.
 */
movement_state: SceneFxState, 
/**
 * Level (0.0..=1.0) of the enabled chaser at capture time, so a
 * re-apply restores the operator's live fader position too.
 */
chaser_master: number | null, 
/**
 * Scene that was playing at capture time. Re-recalled on apply so
 * multi-step scenes resume animating (from step 0).
 */
active_scene_id: string | null, 
/**
 * Loop group that was driving at capture time. Takes precedence
 * over `active_scene_id` on apply (the group recalls its own
 * scenes).
 */
active_loop_group_id: string | null, blackout: boolean, overall_bpm_enabled: boolean, overall_bpm: number, };
