// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SnapshotUniverse = { id: number, 
/**
 * Base-layer DMX values (`Universe.data`) at capture time — manual
 * writes plus whatever the active scene had landed, but *no*
 * effects/blind/master/blackout overlays. Those layers are re-created
 * on apply from the FX/global fields below, so capturing the merged
 * output here would double-count them.
 */
data: Array<number>, };
