// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StreamDeckDeviceInfo = { serial: string, 
/**
 * Human-readable model label (e.g. "Mk2", "XL", "Plus"). The frontend
 * uses this to tell the user *which* Stream Deck got connected.
 */
kind: string, 
/**
 * Number of keys on this kind. The MK.2 has 15; XL has 32.
 */
key_count: number, };
