// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StreamDeckStatus = { 
/**
 * Serial of the currently-connected device, or `None` if disconnected.
 */
connected: string | null, kind: string | null, key_count: number | null, };
