// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ButtonAction } from "./ButtonAction";
import type { ButtonActiveMode } from "./ButtonActiveMode";
import type { ButtonIcon } from "./ButtonIcon";

/**
 * Per-button binding for the Stream Deck MK2 / OriginalV2 5×3 grid.
 * `key` is the 0..=14 index used by elgato-streamdeck.
 */
export type StreamDeckBinding = { key: number, action: ButtonAction, 
/**
 * Short label drawn near the top of the tile. Empty = no label.
 */
label: string, 
/**
 * (R, G, B) for the idle (off) shade. The tile renderer dims this
 * further so a saturated input still reads as "not running".
 */
color_off: [number, number, number], 
/**
 * (R, G, B) for the active (on / pulsing) shade.
 */
color_on: [number, number, number], icon: ButtonIcon, active_mode: ButtonActiveMode, };
