// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Step length expressed as a multiple of one quarter note. The "beat" used
 * for BPM is always a quarter note, so `One` = quarter, `Half` = eighth,
 * `Quarter` = sixteenth, `Two` = half-note, `Four` = whole-note.
 */
export type Subdivision = "quarter" | "half" | "one" | "two" | "four";
