// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SyncSettings } from "./SyncSettings";

/**
 * What the UI needs to render the Sync tab — everything from
 * [SyncSettings] plus a derived "is the PAT set?" flag (we never
 * expose the token itself to the frontend).
 */
export type SyncStatus = { settings: SyncSettings, has_token: boolean, github_user: string | null, };
