// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of a successful push/pull, surfaced in the UI as a toast.
 */
export type SyncResult = { gist_id: string, gist_html_url: string | null, remote_updated_at: string, remote_machine: string | null, };
