// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Probe response: tells the UI whether a push would conflict before
 * the user clicks. Cheap (one GET) and saves a "go back, you have
 * remote changes" round-trip.
 */
export type SyncProbe = { remote_updated_at: string | null, remote_machine: string | null, local_last_remote_updated: string | null, 
/**
 * True when remote has changed since this machine's last
 * successful sync — the caller should warn the user.
 */
remote_ahead: boolean, };
