// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SyncSettings = { 
/**
 * Gist id (the 32-char hex string from the Gist URL). Empty
 * before the user creates / picks a gist.
 */
gist_id: string, 
/**
 * User-friendly label shown in the UI; just the machine name
 * the user types in. Travels with each push as part of the
 * payload so on pull you can see "this came from julio's mac".
 */
machine_label: string, 
/**
 * Default false: outputs are local-machine state. Toggling on
 * includes them in push/pull (use only when both machines run
 * the same OS / same hardware). Off means the outputs config
 * is preserved across pulls.
 */
include_outputs: boolean, 
/**
 * Last `updated_at` we saw on the remote gist. Used to detect
 * "remote changed since we last synced" before push.
 */
last_remote_updated: string | null, 
/**
 * When this machine pushed last.
 */
last_pushed_at: string | null, 
/**
 * When this machine pulled last.
 */
last_pulled_at: string | null, 
/**
 * Label of the machine that pushed the version we saw on the
 * remote last time. UI shows this so you know "the latest
 * remote came from my mac" without guessing.
 */
last_remote_machine: string | null, };
