// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Quantised syncopated rhythm. `bars` × `steps_per_bar` defines a grid;
 * each entry in `hits` is a grid position (0 ≤ pos < bars * steps_per_bar)
 * where a "hit" should fire. The pattern loops every `bars * steps_per_bar`
 * grid units, scaled by the global BPM.
 *
 * Quantising on sixteenth notes (`steps_per_bar = 16`) is the standard for
 * Afro-Cuban / Latin patterns: clave, son, rumba, cha-cha all sit on a 16-
 * step grid in 4/4. The data model also supports two-bar patterns (clave
 * 3-2 vs 2-3 is one bar, but two-bar phrases like clave-with-pickup show
 * up in some folk styles).
 */
export type TempoPattern = { 
/**
 * Number of 4/4 bars the pattern spans. Capped at 2 in the
 * quantiser because longer phrases get hard to play by hand and the
 * 16-step grid loses resolution past two bars.
 */
bars: number, 
/**
 * Resolution of the grid, in steps per bar. Always 16 today
 * (sixteenth notes). Stored so the JSON is self-describing — a
 * future "32nd-note" mode wouldn't break old shows.
 */
steps_per_bar: number, 
/**
 * Grid positions where a hit fires, sorted ascending and unique.
 * Position 0 is always the first hit; subsequent positions are
 * offsets in sixteenth-notes from there.
 */
hits: Array<number>, };
