// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TouchedFixture = { fixture_id: string, 
/**
 * Channel offsets within the fixture mode (0-based) that the
 * operator has written to since the last Clear/Record.
 */
channels: Array<number>, };
