// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VdjConfig = { host: string, port: number, bearer: string | null, interval_ms: number, 
/**
 * Persisted across restarts. When true, the setup hook auto-
 * restarts the poller at boot.
 */
enabled: boolean, 
/**
 * "Halve above" guard: when the VDJ BPM exceeds the threshold,
 * apply BPM/2 to the rig instead. Classic DJ-lighting trick —
 * electronic music at 130 BPM looks like a strobe attack if you
 * drive chasers at 130, but at 65 (half-rate) the rig stays
 * musical and breathes with the bar. Default ON because that's
 * the behaviour the operator wanted out of the box.
 */
halve_above_enabled: boolean, halve_above_threshold: number, };
