// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VdjConfig = { 
/**
 * VirtualDJ host. Almost always `127.0.0.1` because the plugin
 * runs inside the DJ machine, but exposed in case someone runs
 * VDJ on a separate box and our app on another.
 */
host: string, 
/**
 * Network Control Plugin port. The plugin's "default" varies by
 * install — we default to 8080 because port 80 conflicts with
 * anything serving HTTP on the same machine (NGINX, etc.).
 */
port: number, 
/**
 * Bearer token configured in the plugin's settings cogwheel.
 * `None` or empty string ⇒ no Authorization header sent.
 */
bearer: string | null, 
/**
 * How often to poll. 250 ms is a sensible default: fast enough
 * to catch a track change within a beat, slow enough that 4 HTTP
 * calls/second don't show up on any profiler.
 */
interval_ms: number, 
/**
 * Persisted across restarts. When true, the setup hook auto-
 * restarts the poller at boot.
 */
enabled: boolean, };
