// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VdjStatus = { running: boolean, 
/**
 * Last BPM we successfully read from VDJ, regardless of whether
 * we wrote it to the show (epsilon-suppressed writes still
 * update this so the UI can show "yes, we're reading 128.0").
 */
last_bpm: number | null, 
/**
 * Last error string from the polling loop. Cleared on the next
 * successful poll.
 */
last_error: string | null, 
/**
 * Unix seconds of the last successful poll. The UI uses this to
 * render "Last update Xs ago".
 */
last_success_at_secs: bigint | null, };
