// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Waveform = "sine" | "cosine" | "triangle" | "square" | "sawtooth" | "ramp_up" | "ramp_down";
