// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Waveform } from "./Waveform";

export type WaveFunction = { waveform: Waveform, 
/**
 * Multiplier on phase. `1.0` = one full cycle per loop, `2.0` = two.
 */
frequency: number, 
/**
 * Phase shift `0.0..=1.0` applied before the waveform is evaluated.
 */
phase_shift: number, 
/**
 * `0.0..=1.0` scale on the waveform's natural `[-1, 1]` output.
 */
amplitude: number, 
/**
 * Constant added after amplitude — useful for biasing one axis.
 */
offset: number, };
