#!/usr/bin/env node
// Verifies that the TypeScript bindings generated by ts-rs are up to date.
// Strategy:
//   1. Snapshot src/types/ contents.
//   2. Run `cargo test --manifest-path src-tauri/Cargo.toml --lib export_bindings_`
//      which is what ts-rs uses to emit files.
//   3. Compare. If anything differs, fail with a diff list so the user runs the test locally.

import { readFileSync, readdirSync, statSync } from "node:fs";
import { spawnSync } from "node:child_process";
import { join, relative } from "node:path";
import { createHash } from "node:crypto";

const ROOT = new URL("..", import.meta.url).pathname;
const TYPES_DIR = join(ROOT, "src-tauri", "bindings");

function hashDir(dir) {
  const out = {};
  function walk(p) {
    for (const entry of readdirSync(p)) {
      const full = join(p, entry);
      const st = statSync(full);
      if (st.isDirectory()) walk(full);
      else {
        const buf = readFileSync(full);
        out[relative(TYPES_DIR, full)] = createHash("sha256").update(buf).digest("hex");
      }
    }
  }
  try {
    walk(dir);
  } catch {
    // dir might not exist yet
  }
  return out;
}

const before = hashDir(TYPES_DIR);

const cargo = spawnSync(
  "cargo",
  ["test", "--manifest-path", "src-tauri/Cargo.toml", "--lib", "export_bindings_"],
  { cwd: ROOT, stdio: "inherit" },
);
if (cargo.status !== 0) {
  process.exit(cargo.status ?? 1);
}

const after = hashDir(TYPES_DIR);
const allKeys = new Set([...Object.keys(before), ...Object.keys(after)]);
const changed = [];
for (const k of allKeys) {
  if (before[k] !== after[k]) changed.push(k);
}

if (changed.length > 0) {
  console.error("TypeScript bindings out of sync. Re-run cargo test to regenerate:");
  for (const c of changed) console.error(`  - ${c}`);
  process.exit(1);
}
console.log("ts-rs bindings are in sync.");
